# Generated by Django 5.2.5 on 2025-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="transaction_cursor",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
