# Generated by Django 5.2.5 on 2025-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_pendingregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingRegistration",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="data_consent_given",
            field=models.BooleanField(default=False),
        ),
    ]
