# Generated by Django 5.2.5 on 2025-08-25 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_pendingregistration_userprofile_consent_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProvisioning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        default="Automated Access De-provisioning", max_length=200
                    ),
                ),
                ("is_implemented", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CentralizedIAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iam_name",
                    models.CharField(
                        default="Centralized Identity and Access Management",
                        max_length=200,
                    ),
                ),
                ("is_implemented", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        default="Data Retention and Deletion Policy", max_length=200
                    ),
                ),
                ("is_implemented", models.BooleanField(default=True)),
                ("last_reviewed", models.DateTimeField(auto_now=True)),
                (
                    "next_review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZeroTrustArchitecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "architecture_name",
                    models.CharField(
                        default="Zero Trust Access Architecture", max_length=200
                    ),
                ),
                ("is_implemented", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_access_review",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_patch_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_vulnerability_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
